-- src/database/schema.sql
CREATE TABLE IF NOT EXISTS patient_encounters (
    id SERIAL PRIMARY KEY,
    subject_id BIGINT,
    hadm_id BIGINT,
    admission_type VARCHAR(50),
    admission_location VARCHAR(100),
    discharge_location VARCHAR(100),
    insurance VARCHAR(50),
    marital_status VARCHAR(50),
    race VARCHAR(100),
    gender VARCHAR(10),
    anchor_age INT,
    drug VARCHAR(150),
    formulary_drug_cd VARCHAR(100),
    prod_strength VARCHAR(150),
    dose_val_rx VARCHAR(100),
    dose_unit_rx VARCHAR(50),
    form_unit_disp VARCHAR(50),
    route VARCHAR(50),
    eventtype VARCHAR(50),
    careunit VARCHAR(100),
    order_type VARCHAR(50),
    order_subtype VARCHAR(50),
    transaction_type VARCHAR(50),
    spec_type_desc VARCHAR(150),
    test_name VARCHAR(150),
    org_name VARCHAR(150),
    ab_name VARCHAR(150),
    comments TEXT,
    drg_type VARCHAR(50),
    description TEXT,
    drg_severity VARCHAR(50),
    drg_mortality VARCHAR(50)
);